name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code ğŸ›ï¸
        uses: actions/checkout@v4 # <-- REQUIRED STEP: Downloads the repository contents

      - name: Installer Trivy ğŸ“¦
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh

      - name: Scan Trivy du fichier requirements.txt (HIGH + CRITICAL) ğŸ§ª
        run: |
          # The file is now guaranteed to be in $GITHUB_WORKSPACE/requirements.txt
          ./bin/trivy fs "$GITHUB_WORKSPACE/requirements.txt" \
            --format json \
            --severity HIGH,CRITICAL \
          | jq -r '
              ["TARGET","PACKAGE","INSTALLED","VULN","SEVERITY"],
              (.Results[]? as $r 
                | $r.Vulnerabilities[]? 
                | [$r.Target, .PkgName, .InstalledVersion, .VulnerabilityID, .Severity]
              )
              | @tsv' \
          | column -t -s $'\t'
        shell: /usr/bin/bash -e {0}
  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Test Dockerfile
        run: |
          echo "ecrire ici le scrypt de contrÃ´le du Dockerfile"
  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien Ã  faire ici. Votre application est prÃªte Ã  Ãªtre dÃ©ployÃ©e"


